name: build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          git clone -q ${{gitea.server_url}}/${{ gitea.repository }}.git .
          mvn clean install